x-base-backend-template: &backend-template
  image: ghcr.io/your-username/backend:latest
  build:
    context: .
    dockerfile: Dockerfile.dev
    target: backend-dev
  env_file:
    - env

services:
  backend:
    <<: *backend-template
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "wms.wsgi:application", "--workers", "2"]
    depends_on:
      - backend-db

  backend-db:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - env
