# Generated by Django 5.1.7 on 2025-03-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_customuser_role_alter_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Main', 'Main'), ('Production', 'Production'), ('Finished', 'Finished'), ('Shipped', 'Shipped')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'db_table': 'warehouse',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
