# Generated by Django 5.1.7 on 2025-03-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Warehouse Manager', 'Warehouse Manager'), ('Picker/Packer', 'Picker/Packer'), ('Supplier', 'Supplier'), ('Operator', 'Operator')], max_length=255),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
