# Generated by Django 5.1.7 on 2025-03-23 20:05

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.URLField(help_text='Company URL', max_length=255, verbose_name='Company URL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Contact Email', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company Name', max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Warehouse Manager', 'Warehouse Manager'), ('Picker/Packer', 'Picker/Packer')], max_length=255),
        ),
    ]
