# Generated by Django 5.1.7 on 2025-03-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers_alter_company_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.URLField(help_text='Company URL', max_length=255, unique=True, verbose_name='Company URL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Contact Email', max_length=254, unique=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company Name', max_length=255, unique=True, verbose_name='Company Name'),
        ),
    ]
