# Generated by Django 5.1.7 on 2025-03-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_domain_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(help_text='Associated company', on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Warehouse Manager', 'Warehouse Manager'), ('Picker/Packer', 'Picker/Packer')], help_text="User's role in the system", max_length=255, verbose_name='Role'),
        ),
    ]
